Feat/speech function dist book skill
deepmipt/dream pull request #100
Opened 2022-02-18 09:45 UTC by mtalimanchuk

2022-02-18 09:47 UTC, danielkornev approved these changes

2022-02-18 10:31 UTC, danielkornev submitted a review, later dismissed

2022-02-18 15:59 UTC, dilyararimovna requested changes

2022-02-18 15:59 UTC, dilyararimovna commented on annotators/speech_function_classifier/server.py
> +                phrase=sent_tokenize(p.phrase),
мб какая-то проверка, если лист, то уже разбито, если строка, то разбиваем в лист строк (предложений)

2022-02-18 15:59 UTC, dilyararimovna commented on annotators/speech_function_predictor/test_server.py
> +URL = "http://0.0.0.0:8107/model"
почему? надо бы вернуть)

2022-02-18 15:59 UTC, dilyararimovna commented on assistant_dists/dream_sfc/cpu.yml
> +      CUDA_VISIBLE_DEVICES: ""
ну тогда добавьте сюда speech function classisifier (он же нейросетевой сейчас)

2022-02-18 15:59 UTC, dilyararimovna commented on assistant_dists/dream_sfc/proxy.yml
> +      - PROXY_PASS=lnsigo.mipt.ru:8108
пути отличаются. и у предиктора

2022-02-18 15:59 UTC, dilyararimovna commented on skills/dff_book_sfc_skill/server.py
> +    # test_server.run_test(handler)
тесты включите)

2022-02-18 15:59 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +        human_sentseg = dialog["human_utterances"][-2].get("annotations", {}).get("sentseg", {})
а почему берется -2 реплика пользователя? пост-аннотаторы вызываются после выбора финальной реплики, но не обязательно после прихода новой реплики. То есть надо брать -1 реплику бота и реплику пользвоателя, которая в utterances лежит перед этой -1й репликой бота.

2022-02-18 15:59 UTC, dilyararimovna commented on annotators/speech_function_classifier/test_server.py
> +    hypothesis = handler(
добавьте тесты другого ендпоинта (annotation котоырй)

2022-02-18 16:06 UTC, mtalimanchuk commented on annotators/speech_function_classifier/server.py
> +                phrase=sent_tokenize(p.phrase),
я так понял, что сюда только List[AnnotationPayload] попадает, там валидация педантиковская. Или я не понял?

2022-02-18 16:09 UTC, mtalimanchuk commented on assistant_dists/dream_sfc/proxy.yml
> +      - PROXY_PASS=lnsigo.mipt.ru:8108
их пока нет на dream.deeppavlov.ai, вроде будут позже на dream-sfc.deeppavlov.ai или что-то такое

2022-02-18 20:27 UTC, danielkornev commented
Знаем, фиксим заново =)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dilyara Baymurzina ***@***.***>
Sent: Friday, February 18, 2022 11:23:54 PM
To: deepmipt/dream ***@***.***>
Cc: Daniel Kornev ***@***.***>; Review requested ***@***.***>
Subject: Re: [deepmipt/dream] Feat/speech function dist book skill (PR #100)


@dilyararimovna requested changes on this pull request.

________________________________

In state_formatters/dp_formatters.py<https://github.com/deepmipt/dream/pull/100#discussion_r810317127>:

>

-

-def dff_program_y_wide_skill_formatter(dialog: Dict) -> List[Dict]:

-    return utils.dff_formatter(dialog, "dff_program_y_wide_skill")

-

-

-def dff_program_y_skill_formatter(dialog: Dict) -> List[Dict]:

-    return utils.dff_formatter(dialog, "dff_program_y_skill")

+def dff_program_y_formatter(dialog: Dict) -> List[Dict]:

+    return utils.dff_formatter(dialog, "program_y")



верните обратно. тут много что пофикшено зря

—
Reply to this email directly, view it on GitHub<https://github.com/deepmipt/dream/pull/100#pullrequestreview-887725407>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABIFFK6HGSROQLU7HQYLSO3U32TFVANCNFSM5OXLGKZQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2022-02-18 21:23 UTC, danielkornev commented on annotators/speech_function_classifier/server.py
> +                phrase=sent_tokenize(p.phrase),
тут есть ещё вопросы? :)

2022-02-19 13:28 UTC, dilyararimovna approved these changes

2022-02-21 08:25 UTC, IgnatovFedor approved these changes

2022-02-21 08:57 UTC, merged