update entity detection
deepmipt/dream pull request #134
Opened 2022-03-31 07:58 UTC by dmitrijeuseew

2022-04-25 09:49 UTC, dilyararimovna requested changes
![image](https://user-images.githubusercontent.com/14152126/165065204-e380e9df-e4d1-48b5-8222-12f6909225cc.png)
некорректно работает судя по логам в тестах диалога

2022-04-25 09:49 UTC, dilyararimovna commented on annotators/entity_detection/requirements.txt
> +deeppavlov==0.17.2
а почему торч просто сюда не добавить в список зависимостей? зачем он ставиится в контейнере каэждый раз?

2022-04-25 19:02 UTC, dmitrijeuseew commented on annotators/entity_detection/requirements.txt
> +deeppavlov==0.17.2
fixed

2022-04-29 15:22 UTC, dilyararimovna submitted a review, later dismissed

2022-04-29 19:58 UTC, dilyararimovna approved these changes

2022-04-29 20:00 UTC, merged