Feat/transformers intent catcher
deepmipt/dream pull request #135
Opened 2022-04-04 20:31 UTC by dilyararimovna

2022-04-21 12:58 UTC, mtalimanchuk approved these changes

2022-04-21 12:58 UTC, mtalimanchuk commented on annotators/IntentCatcherTransformers/create_data_and_train_model.py
> +# Whereas to calc metrics or not (default value = True)
от старого аргумента остался коммент? мб удалить?

2022-04-21 12:58 UTC, mtalimanchuk commented on annotators/IntentCatcherTransformers/create_data_and_train_model.py
> +# Whereas to calc metrics or not (default value = True)
остальное все ок

2022-04-21 13:27 UTC, mtalimanchuk submitted a review, later dismissed

2022-04-22 21:46 UTC, kudep requested changes
- [x] удалить лишнюю строчку https://github.com/deepmipt/dream/blob/HEAD/assistant_dists/dream/gpu1.yml#L1
- [ ] рекомендую добавить коллбэк на ерли стопинг см (https://huggingface.co/docs/transformers/v4.18.0/en/main_classes/callback#transformers.EarlyStoppingCallback) https://github.com/deepmipt/dream/blob/05f7e7c2262423f8f455d43fdac390cc575ab72b/annotators/IntentCatcherTransformers/create_data_and_train_model.py#L136
- [x] остатки старого кода, который не используется, убарть весь код, который уже не нужен https://github.com/deepmipt/dream/blob/05f7e7c2262423f8f455d43fdac390cc575ab72b/annotators/IntentCatcherTransformers/create_data_and_train_model.py#L17-L22
- [ ] Нужно нормальное сравнение, не понятно что по качеству, из-за дисбаланса класса классификация может быть хуже https://github.com/deepmipt/dream/blob/be03bd6dd18b9d7ddc685fb26884f986b6211c51/annotators/IntentCatcherTransformers/README.md#L10-L18
- [ ] можно добавить сравнение скорость работы IntentCatcher и IntentCatcherTransformers ?

2022-05-13 16:32 UTC, dilyararimovna commented
@kudep @mtalimanchuk я его победила наконец-то, посмотрите потом еще раз, когда время будет. Спасибо!

2022-05-16 13:39 UTC, mtalimanchuk submitted a review, later dismissed

2022-05-18 14:04 UTC, kudep submitted a review, later dismissed

2022-05-18 14:04 UTC, kudep commented
Вроде топ

2022-05-23 11:07 UTC, kudep approved these changes

2022-05-24 07:15 UTC, merged