Conversation evaluator replacement. Manually copied changes from old …
deepmipt/dream pull request #16
Opened 2021-08-22 21:05 UTC by dimakarp1996

…repo

2021-08-23 11:40 UTC, dilyararimovna requested changes
- dev.yml
- docker compose yml
- gpu1.yml
- proxy/yml
- labeled_data json remove!
- очень много файлов поменяно авто тюном. Верни обратно. Изменения только в твоих должны быть. Потому что дрлугие компоненты уже дана другим ребятам, не будем создавать сложностей.

2021-08-23 13:44 UTC, dilyararimovna requested changes

2021-08-23 13:44 UTC, dilyararimovna commented on proxy.yml
> +  cobot-convers-evaluator-annotator:
название

2021-08-23 13:44 UTC, dilyararimovna commented on skills/book_skill/common/books.py
> -ASK_TO_REPEAT_BOOK = "Could you repeat please what book are we discussing?"
что стало с этим файлом?

2021-08-23 13:44 UTC, dilyararimovna commented on skills/book_skill/test_configs/test_dialog.json
> -{"_id": "60a0f260f56ce5682081c946", "dialog_id": "87479cea288c4ffaba364897a44c3359", "utterances": [{"utt_id": "a475751829734eb4d0bc4e0267e31342", "text": "talk about books", "user": {"id": "54e4ef5e
сохрани файл, используя indent
```json.dump(bla, indent=4)```

2021-08-23 13:44 UTC, dilyararimovna commented on skills/grounding_skill/scenario.py
> +            "intent_catcher", {}).get(
откатить файл

2021-08-23 13:46 UTC, dimakarp1996 commented on skills/book_skill/common/books.py
> -ASK_TO_REPEAT_BOOK = "Could you repeat please what book are we discussing?"
Его не должно вообще быть

2021-08-23 13:46 UTC, dimakarp1996 commented on skills/book_skill/common/books.py
> -ASK_TO_REPEAT_BOOK = "Could you repeat please what book are we discussing?"
Он уже есть в common

2021-08-23 13:47 UTC, dimakarp1996 commented on skills/book_skill/common/books.py
> -ASK_TO_REPEAT_BOOK = "Could you repeat please what book are we discussing?"
И при билде он переносится в эту директорию

2021-08-23 13:48 UTC, dimakarp1996 commented on proxy.yml
> +  cobot-convers-evaluator-annotator:
ок

2021-08-23 13:51 UTC, dimakarp1996 commented on skills/grounding_skill/scenario.py
> +            "intent_catcher", {}).get(
ок

2021-08-23 14:16 UTC, dimakarp1996 commented on skills/book_skill/test_configs/test_dialog.json
> -{"_id": "60a0f260f56ce5682081c946", "dialog_id": "87479cea288c4ffaba364897a44c3359", "utterances": [{"utt_id": "a475751829734eb4d0bc4e0267e31342", "text": "talk about books", "user": {"id": "54e4ef5e
ok  (хотя это отдельный пулл-реквест должен быть)

2021-11-19 05:43 UTC, dilyararimovna requested changes

2021-11-19 05:43 UTC, dilyararimovna commented on gpu1.yml
> +  factoid-qa:
убери его, он уже есть в строке 124 в этом же файле

2021-11-19 05:43 UTC, dilyararimovna commented on tests/runtests.sh
> +    #     DOCKER_COMPOSE_CMD="docker-compose -f docker-compose.yml -f dev.yml -f proxy.yml -f s3.yml -p test"
верни обратно, пожалуйста, там же условие выше, если cpu, чтобы потом у кого-нибудь спустя время не было непомнимания

2021-11-19 12:35 UTC, dimakarp1996 commented on gpu1.yml
> +  factoid-qa:
ok

2021-11-19 12:35 UTC, dimakarp1996 commented on tests/runtests.sh
> +    #     DOCKER_COMPOSE_CMD="docker-compose -f docker-compose.yml -f dev.yml -f proxy.yml -f s3.yml -p test"
ok

2021-11-22 15:44 UTC, dilyararimovna approved these changes

2021-11-22 15:45 UTC, merged