Rewrite service from sanic to fastapi. Rewrite tests, configs and doc…
deepmipt/dream pull request #19
Opened 2021-08-26 20:42 UTC by pansershrek

…ker file.

2021-08-31 06:02 UTC, kudep requested changes
- [x] Неправильный запуск сервиса https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/Dockerfile#L12 должен быть как здесь https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/skills/dff_travel_skill/Dockerfile#L32
- [x] обрати внимание на использование ENV нужно использовать переменные среды сделать https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/skills/dff_travel_skill/Dockerfile#L16-L26 надо их использовать таким же образом
- [x] надо добавить хелсчек https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/skills/dff_travel_skill/Dockerfile#L29
- [ ] Описание можно будет поменять в последнюю очередь, но то что здесь написано можно удалять нужно короткое описание в один абзац и максимум команда запуска. Под коротким описание подразумевается написать о том что это сервис основанный на том то, и представляет собой рулбейзый чит-чат https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/README.txt#L5-L55
- [ ] как-то много потребляет https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/README.txt#L60
- [ ] Это дирректория без `.gitkeep` https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/Dockerfile#L10 будет создана от рута 
- [x] надо написать среднее время работы - это миллисекунды
- [ ] Надо server.py сделать ближе к образцу https://github.com/deepmipt/dream/blob/7a86634c463ce41c77aae3b7c4ee1debe413239f/skills/dff_template_skill/server.py#L1-L80 использование переменных среды, тестирование, не нужно исопльзовать `__main__` нужен запуск как у всех остальных сервисов, все с `BaseModel` - оставить
- [x] название констант или данных из переменных среды лождны быть upper case смотри пример из темплейта.
- [x] добавить тестирование при запуске сервера как в темплейте, а не так https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/server.py#L222-L238
- [x] `config.json` закинуть в дата, а текущие данные поместить в `data/storage`
- [ ] поубирать лишние файлы с конфигами
- [ ] что-то страшное свориться в дирректориях `skills/program-y/dream_aiml` надо убрать вложенность, нет причин для хранить большую часть файлов и дирректорий, лишнее удалить, организовать дирректорию наподобии https://github.com/deepmipt/dream/blob/7a86634c463ce41c77aae3b7c4ee1debe413239f/skills/dff_template_skill/
- [x] надо конфигурить сервис через переменные среды,это в особенности касается портов, это убрать из конфига https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/config.json#L18-L23

2021-08-31 13:08 UTC, pansershrek commented
> [x] как-то много потребляет

<img width="1080" alt="Снимок экрана 2021-08-31 в 16 07 43" src="https://user-images.githubusercontent.com/19805374/131507896-25961751-ff06-4f13-9477-dc3d2963d54f.png">

2021-08-31 13:11 UTC, pansershrek commented
> * [x]  Неправильный запуск сервиса https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/Dockerfile#L12
>    должен быть как здесь https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/skills/dff_travel_skill/Dockerfile#L32
> * [x]  обрати внимание на использование ENV нужно использовать переменные среды сделать https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/skills/dff_travel_skill/Dockerfile#L16-L26
>    надо их использовать таким же образом
> * [x]  надо добавить хелсчек https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/skills/dff_travel_skill/Dockerfile#L29
> * [ ]  Описание можно будет поменять в последнюю очередь, но то что здесь написано можно удалять нужно короткое описание в один абзац и максимум команда запуска. Под коротким описание подразумевается написать о том что это сервис основанный на том то, и представляет собой рулбейзый чит-чат https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/README.txt#L5-L55
> * [x]  как-то много потребляет https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/README.txt#L60
> * [x]  Это дирректория без `.gitkeep` https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/Dockerfile#L10
>    будет создана от рута
> * [x]  надо написать среднее время работы - это миллисекунды
> * [x]  Надо server.py сделать ближе к образцу https://github.com/deepmipt/dream/blob/7a86634c463ce41c77aae3b7c4ee1debe413239f/skills/dff_template_skill/server.py#L1-L80
>    использование переменных среды, тестирование, не нужно исопльзовать `__main__` нужен запуск как у всех остальных сервисов, все с `BaseModel` - оставить
> * [x]  название констант или данных из переменных среды лождны быть upper case смотри пример из темплейта.
> * [x]  добавить тестирование при запуске сервера как в темплейте, а не так https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/server.py#L222-L238
> * [x]  `config.json` закинуть в дата, а текущие данные поместить в `data/storage`
> * [x]  поубирать лишние файлы с конфигами
> * [x]  что-то страшное свориться в дирректориях `skills/program-y/dream_aiml` надо убрать вложенность, нет причин для хранить большую часть файлов и дирректорий, лишнее удалить, организовать дирректорию наподобии https://github.com/deepmipt/dream/blob/7a86634c463ce41c77aae3b7c4ee1debe413239f/skills/dff_template_skill/
> * [x]  надо конфигурить сервис через переменные среды,это в особенности касается портов, это убрать из конфига https://github.com/deepmipt/dream/blob/bcc631fe25b82232d9faa0b0b793ecc1045fe43b/skills/program-y/config.json#L18-L23

А что не так  - можете пояснить?

2021-08-31 13:12 UTC, pansershrek commented
> * Это дирректория без `.gitkeep`

А что не так - можете пояснить?

2021-08-31 17:10 UTC, pansershrek commented
Пофиксил

2021-09-02 10:18 UTC, kudep requested changes
- [ ] исопльзовать этот test_server.py по умолчанию https://github.com/deepmipt/dream/blob/f1a5718b4516360f76bc376040fd8ffc9e7b548e/skills/dff_template/test_server.py 
- [ ] вот пример исползвании переменных среды, чтобы не исопльзват по умолчанию https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/docker-compose.yml#L1125-L1139
- [ ] перенести использования радном сида от сюда https://github.com/deepmipt/dream/blob/d165b047743976468b01249090b44b8a52f7e672/docker-compose.yml#L1125-L1139 в handler за пример можно взять https://github.com/deepmipt/dream/blob/7a86634c463ce41c77aae3b7c4ee1debe413239f/skills/dff_template_skill/server.py#L46  это нужно для того чтобы использовать сид если он пришел через запрос см https://github.com/deepmipt/dream/blob/7a86634c463ce41c77aae3b7c4ee1debe413239f/skills/dff_template_skill/server.py#L39

2021-09-02 18:03 UTC, pansershrek commented
Сделал

2021-09-03 01:34 UTC, kudep commented on skills/program-y/.gitignore
> +# Byte-compiled / optimized / DLL files
А можно сделать .gitignore  минимальным, а-то сейчас в нем все лежит, в корне проекта есть .gitignore, все что повторяется можно не добавлять

2021-09-03 08:13 UTC, pansershrek commented on skills/program-y/.gitignore
> +# Byte-compiled / optimized / DLL files
Убрал

2021-09-08 06:37 UTC, kudep commented
- [ ]  Есть набор саджесшенов, которые надо применить в свою ветку (`pr/pansershrek/19_suggestions`  в этой ветки только саджесшены, ее надо смержить с `commonb` чтобы она заработала
- [ ] В ридми ошибки по запуску, без указания докер файла нормальна команда в ридми не отработает . Вот пример который можно вставить 
```
python utils/create_local_yml.py -s program-y
docker-compose -f docker-compose.yml -f local.yml up -d --build program-y
docker-compose -f docker-compose.yml -f local.yml exec program-y bash test.sh
```

- [ ] сам сервис зависает на этапе загрузки модели, надо разобраться почему и пофиксить, проверить это можно следующими командами, сервис остановится на команде `Start to load model`
```
python utils/create_local_yml.py -s program-y
docker-compose -f docker-compose.yml -f local.yml up  --build program-y
```
Рабочая  ветка с мержем и саджесшенами `pr/pansershrek/19_suggestions_merged`

2021-09-08 06:37 UTC, kudep requested changes
Ревью выше

2021-09-09 10:11 UTC, pansershrek commented
Поправил

2021-09-09 16:55 UTC, kudep requested changes
- [x] Это условие проверяется просто "random_seed" in requested_data https://github.com/deepmipt/dream/blob/206e06d48103381862fc8dad930fa0e709899afe/skills/program-y/server.py#L120
- [x] еще можно гитигнор добавиьт только рали этой папочки `logs`

2021-09-09 23:16 UTC, pansershrek commented
Поправил

2021-09-12 08:20 UTC, closed without merging