Feat/sentence ranker as a service
deepmipt/dream pull request #191
Opened 2022-08-23 14:24 UTC by dilyararimovna

2022-08-27 06:57 UTC, kudep reviewed
Can it be also removed ?
```
./annotators/hypothesis_scorer/server.py:43:            "convers_evaluator_annotator": {
./response_selectors/convers_evaluation_based_selector/data_labelling.py:133:            dialog["hypotheses"][i]["annotations"]["convers_evaluator_annotator"] = conv_eval_result["batch"][i]
./response_selectors/convers_evaluation_based_selector/utils.py:140:    if "convers_evaluator_annotator" in hypothesis_annotations:
./response_selectors/convers_evaluation_based_selector/utils.py:141:        cand_scores = hypothesis_annotations["convers_evaluator_annotator"]
./state_formatters/dp_formatters.py:350:def convers_evaluator_annotator_formatter(dialog: Dict) -> List[Dict]:
./state_formatters/dp_formatters.py:930:                "convers_evaluator_annotator": hyp.get("annotations", {}).get("convers_evaluator_annotator", {}),
```

2022-08-27 06:57 UTC, kudep commented
or renamed

2022-08-27 15:04 UTC, kudep requested changes
Fix the comment above, another part  of code is ok

2022-08-29 08:21 UTC, dilyararimovna commented
> Fix the comment above, another part of code is ok

ну мы от `conver_evaluator_annotator` не совсем избавились. Мы добавили альтернативу ему. Все места выше в комменте не требуют изменения

2022-08-29 10:19 UTC, merged