Update dff version of dff-funfact skill
deepmipt/dream pull request #24
Opened 2021-09-02 17:30 UTC by EgSergeenko

This updates dff version of dff-funfact-skill changes tests and updates README.md.

2021-09-08 07:26 UTC, kudep commented
В целом ок, есть немного правок:
- [ ]  `pr/EgSergeenko/24_suggestions ` саджесшены и мерж последней версии `template`
- [ ] В ридми ошибки по запуску, без указания докер файла нормально команда в ридми не отработает . Вот пример который можно вставить 
```
python utils/create_local_yml.py -s dff-template-skills
docker-compose -f docker-compose.yml -f local.yml up -d --build dff-template-skills
docker-compose -f docker-compose.yml -f local.yml exec dff-template-skillsbash test.sh
```

- [ ] Если пользователь попадает в ноду `fallback` - нужно возвращать нулевой конфиденс `set_confidence(ctx, actor, CONF_ZERO)`

2021-09-08 07:33 UTC, kudep requested changes
Ревью выше

2021-09-08 12:45 UTC, EgSergeenko commented
Пофиксил замечания. В тестах оставил `dff-template-skill` вместо `dff-funfact-skill`.

2021-09-09 16:49 UTC, kudep requested changes
Бот не отвечает на второй если попросить следующий фанфакт

2021-09-09 18:31 UTC, kudep approved these changes

2021-09-10 11:37 UTC, kudep approved these changes

2021-09-10 11:38 UTC, merged