COMMoN: COMeT Refactoring
deepmipt/dream pull request #28
Opened 2021-09-06 18:11 UTC by Arsenaut

Сделано:
- Монорепозиторий с comet-commonsense, из которого взят код для инференса моделей, проведён рефакторинг;
- Уменьшил число слоёв в Dockerfile;
- Переписал сервер с Flask на FastAPI;

Осталось сделать:
- Readme.md, notice.md;

Осталось сделать, но столкнулся с проблемой:
- Тесты.

Не до конца понимаю, как сделать тесты для данного случая в предлагаемом формате, потому что есть выбор из разных сэмплеров при инициализации сервиса. В зависимости от выбранного сэмплера меняется и получаемый от сервера ответ. Писать тесты под разные сэмплеры и все их прогонять перед запуском сервера?

2021-09-08 13:34 UTC, kudep requested changes
- [ ] нужно 2  отдельных handler-а  для аннотатора и для простого
- [ ] добавить прогон тестов во время запуска сервиса, если тесты не проходят сервис не запускается (см пример вики)
- [ ] https://github.com/deepmipt/dream/blob/19dbaaca0971260b2aae38bcfbd9d4e8e38a847d/skills/dff_template_skill/test_server.py#L1-L33 сделать все по шаблону, нужен  такой же `test_server.py`, передавать  простой хэндлер не для аннотатора

2021-09-09 23:28 UTC, Arsenaut commented
Замечания исправил, работу над рефакторингом закончил

2021-11-23 11:39 UTC, dilyararimovna submitted a review, later dismissed

2021-12-03 14:04 UTC, mtalimanchuk commented
@Arsenaut CUDA_VISIBLE_DEVICES переиндексирует видимые девайсы, его нельзя прокидывать напрямую в `.to(CUDA_VISIBLE_DEVICES)`
Пример: есть 4 гпу: 0,1,2,3. Выставляем CUDA_VISIBLE_DEVICES=2, теперь нам в коде доступен только "cuda:0", который под капотом маппится на гпу с индексом 2

2021-12-06 10:10 UTC, mtalimanchuk approved these changes

2021-12-06 12:03 UTC, dilyararimovna approved these changes

2021-12-06 12:17 UTC, kudep approved these changes

2021-12-06 12:19 UTC, merged