Commonb fact retrieval refactoring
deepmipt/dream pull request #30
Opened 2021-09-06 18:58 UTC by RomanMatiiv

2021-09-08 12:44 UTC, kudep requested changes
- [ ] тесты не проходят
- [ ] тесты сделать в один в один как в вики за пример можно взять вот этот файл https://github.com/deepmipt/dream/blob/19dbaaca0971260b2aae38bcfbd9d4e8e38a847d/skills/dff_template_skill/test_server.py#L1-L33
- [ ] сможешь ли переписать на fast api?
- [ ] Ридми можно сделать так же https://github.com/deepmipt/dream/blob/ae68219913dd80b62a05c916a70e51481b919fc3/skills/dff_template_skill/README.md (нужно добаить среднее время работы и потребение на gpu  если есть возможность)
- [ ] я так понимаю, PR в целом не дописан, напиши, когда будет готово
- [ ] то, как делать server.py можно посмотреть в #19

2021-12-03 07:55 UTC, dilyararimovna submitted a review, later dismissed

2021-12-03 15:57 UTC, kudep submitted a review, later dismissed

2021-12-03 16:49 UTC, dmitrijeuseew approved these changes

2021-12-06 12:18 UTC, kudep approved these changes

2021-12-06 13:32 UTC, merged