Commonb grounding skill
deepmipt/dream pull request #32
Opened 2021-09-08 18:17 UTC by ms-Anastaisha

2021-09-08 18:49 UTC, kudep requested changes
- [ ] `skills/dff_template_skill/server.py` вернуть в изначальное состояние

2021-09-13 17:11 UTC, kudep submitted a review, later dismissed

2021-10-18 06:11 UTC, dilyararimovna submitted a review, later dismissed

2021-10-18 06:11 UTC, dilyararimovna commented
зарезолвите конфликты

2021-11-30 14:56 UTC, dilyararimovna approved these changes

2021-11-30 14:57 UTC, merged