DFF Refactoring: short-story-skill
deepmipt/dream pull request #33
Opened 2021-09-10 07:24 UTC by akalmanbay

I will add tests in several hours.

2021-09-10 13:04 UTC, kudep requested changes
- [ ] ридми на английском сделать https://github.com/deepmipt/dream/blob/041afc9424321fec356369db56606646c1e57c6e/skills/dff_template_skill/README.md#L3
- [ ] после фразы yes 
![image](https://user-images.githubusercontent.com/11869257/132857305-ffcef846-e50f-4b66-9e9f-202f9b5ae03d.png) бот  отвечает `Oh, sorry, i lost the track of what I was talking about.` 
- [ ] убрать дублирование кода https://github.com/abdulahmedov/dream/blob/4c1e1c6ee408cf72c9291420c21f2474c4c99390/skills/dff_template_skill/scenario/response.py#L20

2021-09-11 21:12 UTC, kudep approved these changes

2021-10-15 12:05 UTC, dilyararimovna commented on skills/dff_template_skill/scenario/processing.py
> -logger = logging.getLogger(__name__)
а куда дели файлик? он не нужен?

2021-10-15 12:09 UTC, dilyararimovna commented on skills/dff_template_skill/scenario/condition.py
> +        re.search("tell", ctx.last_request, re.IGNORECASE) and re.search("story", ctx.last_request, re.IGNORECASE)
а почему это в dff tempalte?

2021-10-15 12:09 UTC, dilyararimovna commented on skills/dff_template_skill/scenario/main.py
> +                        ]
почему этов. dff template?

2021-10-15 12:09 UTC, dilyararimovna commented on skills/dff_template_skill/scenario/response.py
> +    stories = json.load(stories_json)
опять dff tempalte?

2021-11-24 12:32 UTC, kudep commented on skills/dff_short_story_skill/server.py
> +    test_server.run_test(handler)
Надо сид сюда добавить

2021-12-01 13:38 UTC, dilyararimovna approved these changes

2021-12-01 13:38 UTC, merged