Combined classifier with PAL-BERT
deepmipt/dream pull request #45
Opened 2021-10-07 14:35 UTC by dimakarp1996

2021-10-18 09:06 UTC, dilyararimovna commented on common/utils.py
> -            answer_labels = _probs_to_labels(answer_probs, max_proba=True, threshold=0.5)
Есть ощущение, что это убирает совместимость с предыдущим форматом. Верни как было сделай проверку того, что лежит в аннотациях, и в зависимости от этого  - извлекай

2021-10-18 09:06 UTC, dilyararimovna commented on common/utils.py
> -                answer_labels = _probs_to_labels(answer_probs, max_proba=True, threshold=0.5)
Тоже самое

2021-10-21 12:11 UTC, dimakarp1996 commented on common/utils.py
> -                answer_labels = _probs_to_labels(answer_probs, max_proba=True, threshold=0.5)
done

2021-10-21 12:11 UTC, dimakarp1996 commented on common/utils.py
> -            answer_labels = _probs_to_labels(answer_probs, max_proba=True, threshold=0.5)
done

2021-11-08 15:42 UTC, dilyararimovna requested changes

2021-11-08 15:42 UTC, dilyararimovna commented on annotators/news_api/newsapi_service.py
> +                resp = requests.get(url=request_address, timeout=7)
вернуть

2021-11-08 15:42 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +    sentences_with_hist = request.json.get("sentences_with_history", sentences)
а какой у тебя форматтер для гипотез? разве такой ключ есть в нем?

2021-11-08 15:42 UTC, dilyararimovna commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
нет, это не тот вариант проверки вроде, что мы хотим тут делать. При чем тут фактоид. Ты работаешь с токсиком. Можешь сделать такие проверки для определения типа, чтобы не использовать инфу, что за Kin1 combined использвоался

2021-11-08 15:42 UTC, dilyararimovna commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
ниже тоже самое

2021-11-08 17:32 UTC, dimakarp1996 commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
Если factoid in answer_probs, то это значит, что у нас новый формат

2021-11-08 17:33 UTC, dimakarp1996 commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
В зависимости от того, что за Kin1 combined использовался, нам надо ПО-РАЗНОМУ работать с токсиком. В одном случае классификатор решает single label задачу, в другом multilabel. Логично по-разному обрабатывать выход

2021-11-08 17:33 UTC, dimakarp1996 commented on annotators/news_api/newsapi_service.py
> +                resp = requests.get(url=request_address, timeout=7)
ок

2021-11-08 17:46 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +    sentences_with_hist = request.json.get("sentences_with_history", sentences)
ok

2021-11-09 06:36 UTC, dilyararimovna commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
смотри только на классы, которые есть в токсик. Количество вероятностец и пр

2021-11-09 09:38 UTC, dimakarp1996 commented on annotators/combined_classification/combined_classifier.json
> +                "max_seq_length":32,
fixed

2021-11-09 09:40 UTC, dimakarp1996 commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
Я не могу смотреть на количество классов, тк еще давно была договоренность выдавать вероятности не для всех классов, а только для таких классов, у которых она максимальная, соответственно, их количество у выхода аннотатора уже не равно исходному количеству классов. Ты отменяешь эту просьбу?

2021-11-15 07:17 UTC, dilyararimovna requested changes

2021-11-15 07:17 UTC, dilyararimovna commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
нет, не отменяю. но блин чет странно. Я запуталась, в каком формате что приходит

2021-11-15 10:59 UTC, dilyararimovna commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
@dimakarp1996 поняла, как обхяснить почему нельзя. Другие могут упасть сревисы, надо использовать проверки только текущего.

2021-11-15 12:06 UTC, dimakarp1996 commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
То, есть ли factoid in answer_probs - это и есть проверки только текущего

2021-11-15 12:06 UTC, dimakarp1996 commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
То, есть ли factoid in answer_probs - это и есть проверки только текущего

2021-11-15 12:07 UTC, dimakarp1996 commented on common/utils.py
> +        if model_name == "toxic_classification" and "factoid" not in answer_probs:  # old style
Т.к answer_probs - это только то, что выдает МОЙ сервис, а не что-то еще

2021-11-25 06:24 UTC, dilyararimovna approved these changes

2021-11-25 06:27 UTC, merged