Commonb
deepmipt/dream pull request #58
Opened 2021-12-03 19:49 UTC by ruthenian8

dff Book skill in dff_template_skill

2021-12-04 12:16 UTC, kudep requested changes
- [ ] поправить стиль
- [ ] в качестве ключе препроцессоров использовать троки с названиями функций, например `{1: int_prs.set_confidence(SUPER_CONFIDENCE)}` ->`{"set_confidence": int_prs.set_confidence(SUPER_CONFIDENCE)}` это нужно для того, чтобы легко было бы сделать переписывание каких-то препроцессоров с помощью глобал/локал нод, если что вопросы в личку - уточню

2021-12-04 21:27 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +            PROCESSING: {1: int_prs.set_can_continue(MUST_CONTINUE)},
Препроцессинг здесь надо заменить

2021-12-07 16:05 UTC, dilyararimovna approved these changes

2021-12-07 16:06 UTC, dilyararimovna commented
Great Job!

2021-12-07 18:25 UTC, kudep approved these changes

2021-12-07 18:28 UTC, merged